#application_config:
#  run_opts:
##    mem_limit: "2G"
##    memswap_limit: "2G"
#    devices:
#      - /dev/nvidiactl
#      #- /dev/nvidia-uvm-tools
#      - /dev/nvidia-uvm
#      - /dev/nvidia0
#    volumes:
#      /home/z228773/files-pd:
#        bind: /volumes/data
#        mode: ro
#      nvidia_driver_384.130:
#        bind: /usr/local/nvidia
#        mode: ro

{
  "application_config": {
    "run_opts": {
      "volumes": {
        "/home/z228773/files-pd/": {
          "bind":"/volumes/data",
          "mode":"ro"
        }
      }
    }
  },
  "worker_configs": {
    "pack_worker": {
      "gpu": {
        "resource_type":"gpu",
        "card":"auto"
      }
    },
    "train_worker": {
      "gpu": {
        "resource_type":"gpu",
        "card":"auto"
      }
    },
    "benchmark_worker": {
      "gpu": {
        "resource_type":"gpu",
        "card":"auto"
      }
    },
    "train_worker_CaffeBonseyes": {
      "gpu": {
        "resource_type":"gpu",
        "card":"auto"
      }
    },
    "benchmark_worker_CaffeBonseyes": {
      "gpu": {
        "resource_type":"gpu",
        "card":"auto"
      }
    },
    "demo_worker": {
      "gpu": {
        "resource_type":"gpu",
        "card":"auto"
      }
    }
  }
}

