application_config:
  run_opts:
#    mem_limit: "2G"
#    memswap_limit: "2G"
    devices:
      - /dev/nvidiactl
      #- /dev/nvidia-uvm-tools
      - /dev/nvidia-uvm
      - /dev/nvidia0
    volumes:
      /home/z638420/files-pd:
        bind: /volumes/data
        mode: ro
      nvidia_driver_384.130:
        bind: /usr/local/nvidia
        mode: ro
