application_config:
  run_opts:
#    mem_limit: "2G"
#    memswap_limit: "2G"
    devices:
      - /dev/nvidiactl
      #- /dev/nvidia-uvm-tools
      - /dev/nvidia-uvm
      - /dev/nvidia0
    volumes:
      /media/mila/DATOS/BONSEYES/pipeline_Bonseyes/Final/datos_compartidos:
        bind: /volumes/data
        mode: rw
      nvidia_driver_384.111:
        bind: /usr/local/nvidia
        mode: ro
