description: Build all tools

workers:

  build_container:
    type: external
    address:
      type: environment
      name: docker-builder
    output_type: com.bonseyes.docker-image

steps:

  - description: Build normalization training tool
    worker: build_container
    artifact: com.bonseyes.training.base.normalization-training
    parameters:
      context:
        type: workflow-context
      docker_file: pkg/com.bonseyes.training.base/tools/train_normalization/Dockerfile

  - description: Build normalize tool
    worker: build_container
    artifact: com.bonseyes.training.base.normalize
    parameters:
      context:
        type: workflow-context
      docker_file: pkg/com.bonseyes.training.base/tools/normalize/Dockerfile

  - description: Build balanced subset tool
    worker: build_container
    artifact: ch.nviso.training.base.balanced-subset
    parameters:
      context:
        type: workflow-context
      docker_file: pkg/com.bonseyes.training.base/tools/balanced_subset/Dockerfile

  - description: Build dataset_view tool
    worker: build_container
    artifact: com.bonseyes.training.base.dataset_processing-view
    parameters:
      context:
        type: workflow-context
      docker_file: pkg/com.bonseyes.training.base/tools/dataset_view/Dockerfile

  - description: Build zip import tool
    worker: build_container
    artifact: com.bonseyes.training.base.zip-import
    parameters:
      context:
        type: workflow-context
      docker_file: pkg/com.bonseyes.training.base/tools/zip_import/Dockerfile

  - description: Build annotation import tool
    worker: build_container
    artifact: com.bonseyes.training.base.annotations-import
    parameters:
      context:
        type: workflow-context
      docker_file: pkg/com.bonseyes.training.base/tools/annotations_import/Dockerfile