#
# NVISO CONFIDENTIAL
#
# Copyright (c) 2017 nViso SA. All Rights Reserved.
#
# The source code contained or described herein and all documents related to
# the source code ("Material") is the confidential and proprietary information
# owned by nViso or its suppliers or licensors.  Title to the  Material remains
# with nViso SA or its suppliers and licensors. The Material contains trade
# secrets and proprietary and confidential information of nViso or its
# suppliers and licensors. The Material is protected by worldwide copyright and trade
# secret laws and treaty provisions. You shall not disclose such Confidential
# Information and shall use it only in accordance with the terms of the license
# agreement you entered into with nViso.
#
# NVISO MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF
# THE SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
# TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE, OR NON-INFRINGEMENT. NVISO SHALL NOT BE LIABLE FOR
# ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR
# DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
#
version: '3'

services:

  com.bonseyes.training.base.normalization-training:
    build:
        context: ../..
        dockerfile: pkg/com.bonseyes.training.base/tools/train_normalization/Dockerfile
        args:
            - http_proxy
            - https_proxy
            - no_proxy
            - IMAGE_TAG=${BASE_IMAGE_TAG}
            - REGISTRY=${BASE_REGISTRY}
    image: ${REGISTRY}com.bonseyes.training.base.normalization-training:${IMAGE_TAG}

  com.bonseyes.training.base.static-normalization:
    build:
        context: ../..
        dockerfile: pkg/com.bonseyes.training.base/tools/static_normalization/Dockerfile
        args:
            - http_proxy
            - https_proxy
            - no_proxy
            - IMAGE_TAG=${BASE_IMAGE_TAG}
            - REGISTRY=${BASE_REGISTRY}
    image: ${REGISTRY}com.bonseyes.training.base.static-normalization:${IMAGE_TAG}

  com.bonseyes.training.base.normalize:
    build:
        context: ../..
        dockerfile: pkg/com.bonseyes.training.base/tools/normalize/Dockerfile
        args:
            - http_proxy
            - https_proxy
            - no_proxy
            - IMAGE_TAG=${BASE_IMAGE_TAG}
            - REGISTRY=${BASE_REGISTRY}
    image: ${REGISTRY}com.bonseyes.training.base.normalize:${IMAGE_TAG}

  ch.nviso.training.base.balanced-subset:
    build:
        context: ../..
        dockerfile: pkg/com.bonseyes.training.base/tools/balanced_subset/Dockerfile
        args:
            - http_proxy
            - https_proxy
            - no_proxy
            - IMAGE_TAG=${BASE_IMAGE_TAG}
            - REGISTRY=${BASE_REGISTRY}
    image: ${REGISTRY}ch.nviso.training.base.balanced-subset:${IMAGE_TAG}

  com.bonseyes.training.base.dataset-view:
    build:
        context: ../..
        dockerfile: pkg/com.bonseyes.training.base/tools/dataset_view/Dockerfile
        args:
            - http_proxy
            - https_proxy
            - no_proxy
            - IMAGE_TAG=${BASE_IMAGE_TAG}
            - REGISTRY=${BASE_REGISTRY}
    image: ${REGISTRY}com.bonseyes.training.base.dataset_processing-view:${IMAGE_TAG}

  com.bonseyes.training.base.zip-import:
    build:
        context: ../..
        dockerfile: pkg/com.bonseyes.training.base/tools/zip_import/Dockerfile
        args:
            - http_proxy
            - https_proxy
            - no_proxy
            - IMAGE_TAG=${BASE_IMAGE_TAG}
            - REGISTRY=${BASE_REGISTRY}
    image: ${REGISTRY}com.bonseyes.training.base.zip-import:${IMAGE_TAG}

  com.bonseyes.training.base.dataset-import:
    build:
        context: ../..
        dockerfile: pkg/com.bonseyes.training.base/tools/dataset_import/Dockerfile
        args:
            - http_proxy
            - https_proxy
            - no_proxy
            - IMAGE_TAG=${BASE_IMAGE_TAG}
            - REGISTRY=${BASE_REGISTRY}
    image: ${REGISTRY}com.bonseyes.training.base.dataset_processing-import:${IMAGE_TAG}

  com.bonseyes.training.base.annotations-import:
    build:
        context: ../..
        dockerfile: pkg/com.bonseyes.training.base/tools/annotations_import/Dockerfile
        args:
            - http_proxy
            - https_proxy
            - no_proxy
            - IMAGE_TAG=${BASE_IMAGE_TAG}
            - REGISTRY=${BASE_REGISTRY}
    image: ${REGISTRY}com.bonseyes.training.base.annotations-import:${IMAGE_TAG}

  ch.nviso.data-augmentation-quality:
    build:
        context: ../..
        dockerfile: pkg/com.bonseyes.training.base/tools/data_augmentation_quality/Dockerfile
        args:
            - http_proxy
            - https_proxy
            - no_proxy
            - IMAGE_TAG=${BASE_IMAGE_TAG}
            - REGISTRY=${BASE_REGISTRY}
    image: ${REGISTRY}ch.nviso.data-augmentation-quality:${IMAGE_TAG}
