description: "Benchmark model"

parameters:
  model:
    type: resource
  test_set:
    type: resource
  label_map:
    type: resource
    
outputs:
  benchmark_report:
    label: "Benchmark report"

workers:

  benchmark_worker:
    manifest: ./tools/objectdetection_benchmark/manifest.yml

steps:
  - description: "Benchmark a model"
    name: benchmark
    worker: benchmark_worker
    output: benchmark_report
    parameters:
      model: {type: workflow-parameter, name: model}
      test_set: {type: workflow-parameter, name: test_set }
      label_map: { type: workflow-parameter, name: label_map }
      background_class: "22" #Optional. By default, 0
      epochs: "50000" #Optional. By default, 50000
      batch_size: "6" #Optional. By default, 6
