description: "Pipeline Object Detection"

parameters:

  train_images:
    label: "Training images"
    type: resource

  train_labels:
    label: "Training labels"
    type: resource

  test_images:
    label: "Test images"
    type: resource

  test_labels:
    label: "Test labels"
    type: resource

  label_map:
    label: "Labelmap file"
    type: resource


outputs:

  raw_training_dataset:
    label: "Training dataset"

  training_set:
    label: "Training tensor"

  raw_test_dataset:
    label: "Test dataset"

  test_set:
    label: "Test tensor"

  model:
    label: "Model"

  benchmark_report:
    label: "Benchmark report"

  BC_model:
    label: "Model"

  BC_benchmark_report:
    label: "Benchmark report"



workers:

  import_worker:
    manifest: ./tools/objectdetection_import/manifest.yml
  pack_worker:
    manifest: ./tools/objectdetection_pack/manifest.yml
  train_worker:
    manifest: ./tools/objectdetection_train/manifest.yml
  benchmark_worker:
    manifest: ./tools/objectdetection_benchmark/manifest.yml
  train_worker_CaffeBonseyes:
    manifest: ./tools/objectdetection_train_CaffeBonseyes/manifest.yml
  benchmark_worker_CaffeBonseyes:
    manifest: ./tools/objectdetection_benchmark_CaffeBonseyes/manifest.yml



steps:

  - description: "Import training dataset"
    worker: import_worker
    name: import_dataT
    output: raw_training_dataset
    parameters:
      images: { type: workflow-parameter, name: train_images }
      labels: { type: workflow-parameter, name: train_labels }


  - description: "Pack training dataset"
    name: pack_datasetT
    worker: pack_worker
    output: training_set
    parameters:
      raw_dataset: { type: artifact, step: import_dataT }
      label_map: { type: workflow-parameter, name: label_map }

  - description: "Import test dataset"
    worker: import_worker
    name: import_dataB
    output: raw_test_dataset
    parameters:
      images: { type: workflow-parameter, name: test_images }
      labels: { type: workflow-parameter, name: test_labels }

  - description: "Pack test dataset"
    name: pack_datasetB
    worker: pack_worker
    output: test_set
    parameters:
      raw_dataset: { type: artifact, step: import_dataB }
      label_map: { type: workflow-parameter, name: label_map }

  - description: "Train MobileNet-SSD model"
    name: train
    worker: train_worker
    output: model
    parameters:
      training_set: {type: artifact, step: pack_datasetT }
      label_map: { type: workflow-parameter, name: label_map }
      background_class: "22" #Optional. By default, 0
      epochs: "120000" #Optional. By default, 120000
      batch_size: "24" #Optional. By default, 24

  - description: "Benchmark model"
    name: benchmark
    worker: benchmark_worker
    output: benchmark_report
    parameters:
      model: {type: artifact, step: train}
      test_set: {type: artifact, step: pack_datasetB }
      label_map: { type: workflow-parameter, name: label_map }
      background_class: "22" #Optional. By default, 0
      epochs: "50000" #Optional. By default, 50000
      batch_size: "6" #Optional. By default, 6

  - description: "Train a model with caffeBonseyes"
    name: train_CaffeBonseyes
    worker: train_worker_CaffeBonseyes
    output: BC_model
    parameters:
      training_set: {type: artifact, step: pack_datasetT }
      label_map: { type: workflow-parameter, name: label_map }
      model: {type: artifact, step: train}
      background_class: "22" #Optional. By default, 0
      epochs: "120000" #Optional. By default, 120000
      batch_size: "12" #Optional. By default, 12

  - description: "Benchmark model with caffeBonseyes"
    name: benchmark_CaffeBonseyes
    worker: benchmark_worker_CaffeBonseyes
    output: BC_benchmark_report
    parameters:
      model: {type: artifact, step: train_CaffeBonseyes}
      label_map: { type: workflow-parameter, name: label_map }
      test_set: {type: artifact, step: pack_datasetB }
      background_class: "22" #Optional. By default, 0
      epochs: "50000" #Optional. By default, 50000
      batch_size: "6" #Optional. By default, 6
