description: "Pipeline Object Detection"

parameters:

  train_images:
    label: "Training images"
    type: resource

  train_labels:
    label: "Training labels"
    type: resource

  test_images:
    label: "Test images"
    type: resource

  test_labels:
    label: "Test labels"
    type: resource

  label_map:
    label: "Labelmap file"
    type: resource


outputs:

  raw_dataset:
    label: "dataset"

  training_set:
    label: "Training tensor"
    
  model:
    label: "Model"

  benchmark_report:
    label: "Benchmark report"



workers:

  import_worker:
    manifest: ./tools/objectdetection_import/manifest.yml
  pack_worker:
    manifest: ./tools/objectdetection_pack/manifest.yml
  train_worker:
    manifest: ./tools/objectdetection_train/manifest.yml
  benchmark_worker:
    manifest: ./tools/objectdetection_benchmark/manifest.yml  
#  train_worker_CaffeBonseyes:
#    manifest: ./tools/objectdetection_train_CaffeBonseyes/manifest.yml
#  benchmark_worker_CaffeBonseyes:
#    manifest: ./tools/objectdetection_benchmark_CaffeBonseyes/manifest.yml



steps:

  - description: "Import training dataset"
    worker: import_worker
    name: import_dataT
    output: raw_dataset
    parameters:
      images: { type: workflow-parameter, name: train_images }
      labels: { type: workflow-parameter, name: train_labels }


  - description: "Pack training dataset"
    name: pack_datasetT
    worker: pack_worker
    output: training_set
    parameters:
      raw_dataset: { type: artifact, step: import_dataT }
      label_map: { type: workflow-parameter, name: label_map }

  - description: "Import test dataset"
    worker: import_worker
    name: import_dataB
    output: raw_dataset
    parameters:
      images: { type: workflow-parameter, name: test_images }
      labels: { type: workflow-parameter, name: test_labels }
      

  - description: "Pack test dataset"
    name: pack_datasetB
    worker: pack_worker
    output: training_set
    parameters:
      raw_dataset: { type: artifact, step: import_dataB }
      label_map: { type: workflow-parameter, name: label_map }
 
      
  - description: "Train MobileNet-SSD model"
    name: youtube_model
    worker: train_worker
    output: model
    parameters:
      training_set: {type: artifact, step: pack_datasetT }
      label_map: { type: workflow-parameter, name: label_map }
      epochs: "10" #"12000"
      batch_size: "5" #Optional. By default, 24
      
  - description: "Benchmark model"
    name: benchmark
    worker: benchmark_worker
    output: benchmark_report
    parameters:
      model: {type: artifact, step: youtube_model}
      test_set: {type: artifact, step: pack_datasetB }
      label_map: { type: workflow-parameter, name: label_map }
      epochs: "10" #"5000"
      batch_size: "5" #Optional. By default, 12

#  - description: "Train a model with caffeBonseyes"
#    name: youtube_model_CaffeBonseyes
#    worker: train_worker_CaffeBonseyes
#    output: model
#    parameters:
#      training_set: {type: artifact, step: pack_datasetT }
#      model: {type: artifact, step: youtube_model}
#      epochs: "10" #"28000"
#      batch_size: "5" #Optional. By default, 28000
#
#  - description: "Benchmark a model"
#    name: benchmark_CaffeBonseyes
#    worker: benchmark_worker_CaffeBonseyes
#    output: benchmark_report
#    parameters:
#      model: {type: artifact, step: youtube_model_CaffeBonseyes}
#      test_set: {type: artifact, step: pack_datasetB }
#      epochs: "10" #"5000"
#      batch_size: "5" #Optional. By default, 28000
