description: "Train model with SSD + MobileNet"

parameters:
  training_set:
    type: resource
  label_map:
    type: resource
    label: "Labelmap file"

outputs:
  model:
    label: "Model"

workers:
  train_worker:
    manifest: ./tools/objectdetection_train/manifest.yml

steps:
  - description: "Train a model"
    name: youtube_model
    worker: train_worker
    output: model
    parameters:
      training_set: {type: workflow-parameter, name: training_set }
      label_map: { type: workflow-parameter, name: label_map }
      background_class: "22" #Optional. By default, 0
      epochs: "5" #Optional. By default, 28000
      batch_size: "5" #Optional. By default, 24
