description: "Create a model with the training lmdb and benchmark it on the test lmdb"

outputs:

  model:
    label: "Model"

  benchmark_report:
    label: "Benchmark report"

workers:
  train_worker:
    manifest: ./tools/objectdetection_train/manifest.yml
  benchmark_worker:
    manifest: ./tools/objectdetection_benchmark/manifest.yml

steps:

  - description: "Train a model"
    name: youtube_model
    worker: train_worker
    output: model
    parameters:
      training_set: "./youtube-bb_trainval_lmdb/data.mdb"
        #name: training_set
        #type: string #{type: workflow-parameter, name: training_set }
      epochs: "2800"

  - description: "Benchmark a model"
    name: benchmark
    worker: benchmark_worker
    output: benchmark_report
    parameters:
      model: {type: artifact, step: youtube_model}
      epochs: "2800"
