description: "Sparsify a model"

workers:

  train:
    manifest: ./pkg/com.bonseyes.training.caffe/tools/train/manifest.yml

parameters:

    model_architecture:
      label: "Model architecture"
      type: "resource"
    test_dataset:
      label: "test dataset"
      type: "resource"
    dataset:
      label: "Data train tensor"
      type: "resource"
    solver_config:
      label: "solver parameters"
      type: "resource"


steps:

  - description: "train model"
    worker: train
    artifact: caffe_model
    parameters:
      model_architecture:
        type: workflow-parameter
        name: model_architecture
      test_dataset:
        type: workflow-parameter
        name: test_dataset
      dataset:
        type: workflow-parameter
        name: dataset
      solver_config:
        type: workflow-parameter
        name: solver_config

  - description: "Wait for user"
    wait:
